details:
  namespace: student123-bookinfo-dev
  image: ghcr.io/l-nattakron/bookinfo-details
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
ingress:
  host: bookinfo.dev.opsta.net
  path: "/student123/details(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2